:menus:
  - { :title: SKIP公式サイト, :url: http://www.openskip.org/ }
  - { :title: SKIPポータル, :url: http://portal.openskip.org/ }
  - { :title: SKIPユーザコミュニティ, :url: http://user.openskip.org/ }
#   - :title: 開発
#     :links:
#     - { :title: Repository, :url: http://github.com/openskip/skip/ }
#     - { :title: redmine, :url:  http://dev.openskip.org/redmine/ }
#   - :title: 関連サイト
#     :links:
#     - { :title: Ruby On Rails, :url:   http://www.rubyonrails.org/ }
